  ### Day - 01

In [3]:
import  numpy  as  np

arr = np.array([2,1,4,5,8])

print(arr)

print("type", type(arr))
print("shape" , np.shape(arr))

[2 1 4 5 8]
type <class 'numpy.ndarray'>
shape (5,)


In [4]:
a =  np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a + b)

[ 6  8 10 12]


In [10]:
zeros =  np.zeros((2,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones  = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


arr = np.arange(0,100, 11)
print(arr)

In [15]:
arr = np.linspace(10,100,3)
print(arr)

[ 10.  55. 100.]
