  ### Day - 01

In [1]:
import  numpy  as  np

arr = np.array([2,1,4,5,8])

print(arr)

print("type", type(arr))
print("shape" , np.shape(arr))

[2 1 4 5 8]
type <class 'numpy.ndarray'>
shape (5,)


In [2]:
a =  np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a + b)

[ 6  8 10 12]


In [3]:
zeros =  np.zeros((2,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
ones  = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


arr = np.arange(0,100, 11)
print(arr)

In [5]:
arr = np.linspace(10,100,3)
print(arr)

[ 10.  55. 100.]


In [6]:
arr = np.ones((3,3))
arr[1][1] =  9

print(arr)

[[1. 1. 1.]
 [1. 9. 1.]
 [1. 1. 1.]]


In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(2, 3)
2
6
int64
8


#### Indexing & Slicing


In [11]:
arr =  np.array([10,20,30,40,50,60,70,80])
print(arr[0])
print(arr[-1])
print(arr[-2])

10
80
70


In [12]:
arr = np.arange(1,17).reshape(4,4)

print(arr)1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
